COMPILER = g++
FLAGS = -o
EXE = prog
SRC = *.cpp *.h
LINK = -lopencv_core -lopencv_highgui -lopencv_imgproc

#compiling
main:
	$(COMPILER) $(SRC) $(LINK) $(INCLUDE) $(FLAGS) $(EXE)
	
run:
	@echo "running the program"
	./$(EXE)

